spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

spring.main.allow-bean-definition-overriding: true

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
